spring.application.name=CadastroAluno

spring.datasource.url=jdbc:postgresql://pg-16a6caca-laraproject1.g.aivencloud.com:23435/db_student?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_rGprdCInCguC8PhWlge
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000

jwt.secret=dGhpc0lzQVN1cGVyU2VjdXJlS2V5Rm9ySldUMjAyNlN5c3RlbUVzY29sYQ==